### ISSUE TITLE
Post schema 4.0.0 release checklist

### ISSUE THREAD

**Issue by annakrystalli** [hubverse-org/hubValidations#158]
- [x] remove `br-v4.0.0` mention (done in release PR)
- [x] add back ` (>= 0.3.0)` as a minimum version requirement for `hubUtils` (done in release PR)
- [x] remove pull request remote reference for `hubUtils`(done in release PR)
- [x] Remove unnecessary warning suppression
- [x] re-snapshot
